# Site settings
title: "星辰的漫遊構成了時間"
bye_message: "Bienvenue"
baseurl: "/cmz/"
url: "https://vyej.github.io/cmz"


paginate: 3



# Build settings
markdown: kramdown
permalink: /:categories/:title/



plugins:
  - jekyll-paginate
