name: C-M-z 星辰的漫遊構成了時間
url: https://vyej.github.io/cmz
description: Evaluates the current region >----  Moriatur anima meamortem philisophorum.

baseurl: '/cmz'

permalink: /:year/:month/:day/:title/
paginate: 3

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
